# Generated by Django 4.2.27 on 2026-01-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="herbalproduct",
            name="meta_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="herbalproduct",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="herbalproduct",
            name="meta_title",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="herbalproduct",
            name="slug",
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
